### ISSUE TITLE
Feature Request: Settings for Debug Verbosity and Visibility to Players

### ISSUE THREAD

**Issue by Greysion** [schultzcole/FVTT-Autocomplete-Inline-Properties#17]
Hello!

I was hoping you might be able to add a toggle for the verbosity of the error logging in Foundry.

Currently if (for whatever reason) I am editing an inline property of a character and either make a mistake or it triggers a debug message upon opening all players will see the full report.

The ability to disable these popups entirely for players would be wonderful.

Otherwise, this mod has been an incredible improvement to the GM workflow and I appreciate all of your efforts immensely.

Thanks!

**Comment by schultzcole** [comment]
Hi @Greysion, sorry for not responding earlier. This issue is unfortunately an caused by how the core software prepares actor and item data. The way it is set up, all clients will prepare the data for all world entities, so if there is a mistake in any entity, all clients will get a warning that preparation failed. As far as I know there isn't a way to bypass this.
