### ISSUE TITLE
Unable to add new PACKAGE_CONFIG objects

### ISSUE THREAD

**Issue by asacolips** [schultzcole/FVTT-Autocomplete-Inline-Properties#20]
Foundry Version: 0.8.6
System Version: Toolkit13 1.11.0
Autocomplete Inline Properites Version: 2.1.1

I had previously added support to AIP in the Toolkit13 (13th Age Compatible) system, but realized today that the API has changed and my configuration was no longer applying. After reviewing the docs, it looks like that's moved to `game.modules.data('autocomplete-inline-properties').API`.

However, the docs recommend placing this in the init hook (https://github.com/schultzcole/FVTT-Autocomplete-Inline-Properties/blob/master/CONTRIBUTING.md#example), but in the module's own init hook, the API object is reinitialized. Because modules are executed after systems, my changes seem to be unable to apply and are overwritten.

I've also tried adding my configuration in the ready hook, and while they do exist in the config if I do it that way, they do not appear to function (I'm assuming that's due to the config existing too late in the process).

**Comment by schultzcole** [comment]
Ah, you're right. AIP creates the base package config in the init hook, and processes the package config in the setup hook, so anything added in init might be too early, and anything added in ready will be too late.

I think for a system you could add it during setup and it would work, but that won't work for other modules. I'll see what the best option is and will get back to you.

**Comment by schultzcole** [comment]
So there are a couple of options I am considering:

1. I could mark AIP as a library package, which would guarantee that it will load before other non library packages, meaning that `game.modules.data('autocomplete-inline-properties').API` should exist by the time you try to use it in the "init" hook.
2. I could process the package configuration in the ready hook. So it originally gets created in the init hook, modules and systems can modify it in setup, then it gets used in ready.

To me it seems like 1 is the better option, because other packages don't need to change anything to be compatible. It might be stretching the definition of "library", but I think it fits the intended purpose closely enough. Do you have any thoughts on that @asacolips?

**Comment by asacolips** [comment]
@schultzcole I was able to get it working with the setup hook, so I think just updating the docs should cover it. Thanks for the suggestion!

**Comment by schultzcole** [comment]
Ok, I'll go ahead and close this issue then
